

user_show:
  path: /user
  controller: App\User\Controller\Show
  methods: ['GET']

user_listing:
  path: /users
  controller: App\User\Controller\Listing
  methods: ['GET']

user_create:
  path: /user_create
  controller: App\User\Controller\Create
  methods: ['GET', 'POST']

user_edit:
  path: /{id}
  controller: App\User\Controller\Edit
  methods: ['GET', 'POST']