reservation_listing:
  path: /reservation
  controller: App\Reservation\Controller\Listing
  methods: ['GET']

reservation_create:
  path: /reservation/create
  controller: App\Reservation\Controller\Create
  methods: ['GET', 'POST']

reservation_edit:
  path: /reservation/edit/{id}
  controller: App\Reservation\Controller\Edit
  methods: ['GET', 'POST']