doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Core:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'App\Core\Entity'
                alias: App
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: App
            Place:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Place/Entity'
                prefix: 'App\Place\Entity'
                alias: App
            Treatment:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Treatment/Entity'
                prefix: 'App\Treatment\Entity'
                alias: App
            Reservation:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Reservation/Entity'
                prefix: 'App\Reservation\Entity'
                alias: App
            TherapyRoom:
                is_bundle: false
                dir: '%kernel.project_dir%/src/TherapyRoom/Entity'
                prefix: 'App\TherapyRoom\Entity'
                alias: App
            Room:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Room/Entity'
                prefix: 'App\Room\Entity'
                alias: App
            RehabilitationStay:
                is_bundle: false
                dir: '%kernel.project_dir%/src/RehabilitationStay/Entity'
                prefix: 'App\RehabilitationStay\Entity'
                alias: App
            PlannedStay:
                is_bundle: false
                dir: '%kernel.project_dir%/src/PlannedStay/Entity'
                prefix: 'App\PlannedStay\Entity'
                alias: App


        

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
