<?php

namespace ContainerTxxWA9M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatePostCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Post\Command\CreatePostCommand' shared autowired service.
     *
     * @return \App\Post\Command\CreatePostCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Post/Command/CreatePostCommand.php';

        $container->privates['App\\Post\\Command\\CreatePostCommand'] = $instance = new \App\Post\Command\CreatePostCommand(($container->privates['App\\Post\\Service\\CreatePost'] ?? $container->load('getCreatePostService')));

        $instance->setName('app:create-post');

        return $instance;
    }
}
