<?php

namespace ContainerJ75x2fS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaker_DoctrineHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'maker.doctrine_helper' shared service.
     *
     * @return \Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Doctrine/DoctrineHelper.php';

        $a = ($container->privates['doctrine.orm.default_annotation_metadata_driver'] ?? $container->getDoctrine_Orm_DefaultAnnotationMetadataDriverService());

        return $container->privates['maker.doctrine_helper'] = new \Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper('App\\Entity', ($container->services['doctrine'] ?? $container->getDoctrineService()), ['default' => [0 => [0 => 'App\\Core\\Entity', 1 => ($container->privates['doctrine.orm.default_attribute_metadata_driver'] ??= new \Doctrine\ORM\Mapping\Driver\AttributeDriver([0 => (\dirname(__DIR__, 4).'/src/Core/Entity')]))], 1 => [0 => 'App\\User\\Entity', 1 => $a], 2 => [0 => 'App\\Post\\Entity', 1 => $a]]]);
    }
}
