place:
    resource: '../src/Place/config/routes.yaml'

user:
    resource: '../src/User/config/routes.yaml'

reservation:
    resource: '../src/Reservation/config/routes.yaml'

treatment:
    resource: '../src/Treatment/config/routes.yaml'

therapy_room:
    resource: '../src/TherapyRoom/config/routes.yaml'

treatment_type:
    resource: '../src/TreatmentType/config/routes.yaml'

room:
    resource: '../src/Room/config/routes.yaml'

rehabilitation_stay:
    resource: '../src/RehabilitationStay/config/routes.yaml'

planned_stay:
    resource: '../src/PlannedStay/config/routes.yaml'

user_reservation:
    resource: '../src/UserReservation/config/routes.yaml'

treatment_plan:
    resource: '../src/TreatmentPlan/config/routes.yaml'


controllers:
    resource:
        path: ../src/Core/Controller/
        namespace: App\Core\Controller
    type: attribute
    
User_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute


home:
    path: /home
    controller: App\Core\Controller\HomeController::index
    methods: ['GET']

welcome:
    path: /
    controller: App\Core\Controller\HomeController::welcome
    methods: ['GET']
    
access_denied:
    path: /access_denied
    controller: App\Core\Controller\AccessDenied
    methods: ['GET']









