controllers:
    resource:
        path: ../src/Core/Controller/
        namespace: App\Core\Controller
    type: attribute
    
User_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute
    
Post_controllers:
    resource:
        path: ../src/Post/Controller/
        namespace: App\Post\Controller
    type: attribute


home:
    path: /home
    controller: App\Core\Controller\HomeController::index
    methods: ['GET']

    
    
welcome:
    path: /
    controller: App\Core\Controller\HomeController::welcome
    methods: ['GET']

reservation_listing:
    path: /reservation
    controller: App\Reservation\Controller\Listing
    methods: ['GET']


user_show:
    path: /user/show
    controller: App\User\Controller\Show
    methods: ['GET']