# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*/'
        exclude:
            - '../src/*/DependencyInjection/'
            - '../src/*/Entity/'
            - '../src/*/Kernel.php'
            
    App\Core\Controller\:
        resource: '../src/Core/Controller'
        tags: ['controller.service_arguments']
        
    App\User\Controller\:
        resource: '../src/User/Controller'
        tags: ['controller.service_arguments']
        
    App\Post\Controller\:
        resource: '../src/Post/Controller'
        tags: ['controller.service_arguments']
        
    App\Core\Twig\:
        resource: '../src/Core/Twig/*'
        arguments: ["@service_container", "@twig", "@router"]
        

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
