treatment_show:
  path: /treatment-show
  controller: App\Treatment\Controller\Listing
  methods: ['GET']

treatment_create:
  path: /treatment-create
  controller: App\Treatment\Controller\Create
  methods: ['GET', 'POST']