<?php

namespace ContainerRLPT6wS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Reservation\Controller\Create' shared autowired service.
     *
     * @return \App\Reservation\Controller\Create
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Reservation/Controller/Create.php';

        return $container->services['App\\Reservation\\Controller\\Create'] = new \App\Reservation\Controller\Create();
    }
}
