<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0sVI5xJ\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0sVI5xJ/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container0sVI5xJ.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container0sVI5xJ\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container0sVI5xJ\App_KernelTestDebugContainer([
    'container.build_hash' => '0sVI5xJ',
    'container.build_id' => '54742073',
    'container.build_time' => 1684174976,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0sVI5xJ');
