<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home' => [[], ['_controller' => 'App\\Core\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'createUser' => [[], ['_controller' => 'App\\Core\\Controller\\HomeController::createUser'], [], [['text', '/createUser']], [], [], []],
    'bezpieczna' => [[], ['_controller' => 'App\\Core\\Controller\\HomeController::secure'], [], [['text', '/bezpieczna']], [], [], []],
    'admin_users' => [[], ['_controller' => 'App\\Core\\Controller\\HomeController::adminUsers'], [], [['text', '/admin/users']], [], [], []],
    'welcome' => [[], ['_controller' => 'App\\Core\\Controller\\HomeController::welcome'], [], [['text', '/']], [], [], []],
    'registration' => [[], ['_controller' => 'App\\User\\Controller\\AuthController::registration'], [], [['text', '/rejestracja']], [], [], []],
    'login' => [[], ['_controller' => 'App\\User\\Controller\\AuthController::login'], [], [['text', '/logowanie']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\User\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], [], []],
    'post' => [[], ['_controller' => 'App\\Post\\Controller\\PostController::create'], [], [['text', '/post']], [], [], []],
];
