planned_stay_listing:
  path: /plannedstay/listing
  controller: App\PlannedStay\Controller\Listing
  methods: ['GET']

planned_stay_create:
  path: /plannedstay/create
  controller: App\PlannedStay\Controller\Create
  methods: ['GET', 'POST']

planned_stay_show:
  path: /plannedstay/show/{id}
  controller: App\PlannedStay\Controller\Show
  methods: ['GET']

planned_stay_edit:
  path: /plannedstay/edit/{id}
  controller: App\PlannedStay\Controller\Edit
  methods: ['GET', 'POST']

planned_stay_delete:
  path: /plannedstay/delete/{id}
  controller: App\PlannedStay\Controller\Delete
  methods: ['GET']