<?php

namespace ContainerM99QE2T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\User\Controller\AuthController' shared autowired service.
     *
     * @return \App\User\Controller\AuthController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/User/Controller/AuthController.php';

        $container->services['App\\User\\Controller\\AuthController'] = $instance = new \App\User\Controller\AuthController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\User\\Controller\\AuthController', $container));

        return $instance;
    }
}
