<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4wPM7h2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4wPM7h2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4wPM7h2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4wPM7h2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4wPM7h2\App_KernelDevDebugContainer([
    'container.build_hash' => '4wPM7h2',
    'container.build_id' => 'c3254a4b',
    'container.build_time' => 1683900581,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4wPM7h2');
