<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyEJOdg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyEJOdg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHyEJOdg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHyEJOdg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHyEJOdg\App_KernelDevDebugContainer([
    'container.build_hash' => 'HyEJOdg',
    'container.build_id' => '369c4b86',
    'container.build_time' => 1694103829,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyEJOdg');
