<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL5SYg5b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL5SYg5b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL5SYg5b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL5SYg5b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL5SYg5b\App_KernelDevDebugContainer([
    'container.build_hash' => 'L5SYg5b',
    'container.build_id' => '30fb4bf0',
    'container.build_time' => 1684160203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL5SYg5b');
