<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'places_listing' => [[], ['_controller' => 'App\\Place\\Controller\\Listing'], [], [['text', '/places_listing']], [], [], []],
    'place_edit' => [[], ['_controller' => 'App\\Place\\Controller\\Edit'], [], [['text', '/place_edit']], [], [], []],
    'place_create' => [[], ['_controller' => 'App\\Place\\Controller\\Create'], [], [['text', '/place_create']], [], [], []],
    'user_show' => [[], ['_controller' => 'App\\User\\Controller\\Show'], [], [['text', '/user']], [], [], []],
    'user_listing' => [[], ['_controller' => 'App\\User\\Controller\\Listing'], [], [['text', '/users']], [], [], []],
    'reservation_listing' => [[], ['_controller' => 'App\\Reservation\\Controller\\Listing'], [], [['text', '/reservation']], [], [], []],
    'registration' => [[], ['_controller' => 'App\\User\\Controller\\AuthController::registration'], [], [['text', '/rejestracja']], [], [], []],
    'login' => [[], ['_controller' => 'App\\User\\Controller\\AuthController::login'], [], [['text', '/logowanie']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\User\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Core\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'welcome' => [[], ['_controller' => 'App\\Core\\Controller\\HomeController::welcome'], [], [['text', '/']], [], [], []],
    'access_denied' => [[], ['_controller' => 'App\\Core\\Controller\\AccessDenied'], [], [['text', '/access_denied']], [], [], []],
    'treatments_show' => [[], ['_controller' => 'App\\Treatment\\Controller\\Show'], [], [['text', '/treatments_show']], [], [], []],
];
